site_name: CyberTraining
site_author: ' slehee'
copyright: Copyright &copy; 2025 slehee
nav:
    - PrivEsc:
        - Linux: 
            - linux.md
            - Practice machines:
               - ultratech.md   
               - lazy admin.md  
               - anonymous.md
               - ghostcat.md
               - convert.md
               - titanic.md


theme:
    name: material
    logo: assets/bb.png
    favicon: assets/Boba.png
    features:
      - content.tabs.link  
      - navigation.instant  
      - navigation.tracking
      - navigation.tabs
    icon:
      admonition:
        note: octicons/tag-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/squirrel-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
    palette:
      - scheme: default
        primary: indigo
        accent:  indigo
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - scheme: slate
        primary: deep purple
        accent: deep purple
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode

markdown_extensions:
  - admonition
  - smarty
  - md_in_html
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.superfences
  - pymdownx.tilde
  - footnotes
  - plantuml_markdown:
      format: svg
      server: http://www.plantuml.com/plantuml
  - pymdownx.superfences:
  - pymdownx.tasklist:
          clickable_checkbox: true
          custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      baselevel: 2

plugins:
    - macros
    - search 
    - with-pdf:
        cover_subtitle: ''
        output_path: pdf/E.pdf
        enabled_if_env: ENABLE_PDF_EXPORT 
        